version: 2
jobs:
  build:
    # docker-composeがインストール済みの仮想マシンをプル
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: database.ymlの再設定
          command: |
            rm ./config/database.yml
            mv ./config/database.ci.yml ./config/database.yml
      - run:
          name: Dockerビルド
          command: docker-compose build
      - run:
          name: Docker起動
          command: docker-compose up -d
      # - run:
      #     name: sleep for waiting launch db
      #     command: sleep 1
      - run:
          name: データベースのセットアップ
          # command: docker-compose run web rails db:create db:migrate
          command: docker-compose exec web bundle exec rails db:create db:migrate RAILS_ENV=test
      - run:
          name: RSpecテスト実行
          # command: docker-compose run web rspec
          command: docker-compose exec web bundle exec bin/rspec
      - run:
          name: Rubocopテスト実行
          # command: docker-compose run web rspec
          command: docker-compose exec web bundle exec rubocop
      - run:
          name: Docker停止
          command: docker-compose down
workflows:
  version: 2
  build:
    jobs:
      - build
